[
    "Anthony Schmitz",
    "Austin Piecuch",
    "Brendan O'Donohue",
    "Caleb Ulman",
    "Carter Nagel",
    "Coach Maccoroni",
    "Coach Scully",
    "Connor O'Donohue",
    "Dom Rolf",
    "Dominic Schmitz",
    "Eli Ashby",
    "Eli Hakes",
    "Eli Miller",
    "Haegan Land",
    "Ike Schoenborn",
    "Isaac Skinner",
    "Jack Major",
    "Joe Engle",
    "John DiPiazza",
    "John Lydel",
    "John Paul Sanders",
    "John Warner",
    "Josh Ulman",
    "Josiah Miller",
    "Kaelan Miller",
    "Morgan Duddles",
    "Nathan Ulman",
    "Noah Kwiatkowski",
    "Noah Lewandowsk",
    "Stratton Land"
]

[
    "Alysa Peebles",
    "Amelia Adkins",
    "Anasophia Schmitz",
    "Ashley Zimmerman",
    "Brailyn Johnson",
    "Chloe Nagel",
    "Claire Engle",
    "Daisy Speet",
    "Elicia Land",
    "Evie Hakes",
    "Gianna Dugan",
    "Gloria Gaston",
    "Jana Stiffler",
    "Jasmine Zimmerman",
    "Jessalyn Rolf",
    "Kate O'Donohue",
    "Maggie Prina",
    "Meghan VanDalen",
    "Molly Finkler",
    "Natalie Sanders",
    "Polly Weis",
    "Sadie Hakes",
    "Stephanie DiPiazza",
    "Suzannah DiPiazza",
    "Valley Duddles"
]



/*

backup bruh
{"tags":["XC","track","in-season","off-season","team","meet","practice","summer-training","group","food","social","mid-race","solo","J-Squad","sacred-heart"],"names":[
    "Alysa Peebles",
    "Amelia Adkins",
    "Anasophia Schmitz",
    "Anthony Schmitz",
    "Ariston Churchwell",
    "Ashley Zimmerman",
    "Aurora Keefer",
    "Austin Piecuch",
    "Ava Skinner",
    "Avery Graham",
    "Blythe Webb",
    "Brailyn Johnson",
    "Brendan O'Donohue",
    "Caleb Ulman",
    "Carter Nagel",
    "Chloe Nagel",
    "Claire Engle",
    "Coach Hakes",
    "Coach Kwiatkowski",
    "Coach Maccoroni",
    "Coach McCrory",
    "Coach O'Donohue",
    "Coach Scully",
    "Connor O'Donohue",
    "Daisy Speet",
    "Dom Rolf",
    "Dominic Schmitz",
    "Eli Ashby",
    "Eli Hakes",
    "Eli Miller",
    "Eli Skinner",
    "Elicia Land",
    "Elijah Cullen",
    "Elijah Kwiatkowski",
    "Evan King",
    "Evie Hakes",
    "Evie Sanders",
    "Gianna Dugan",
    "Girl In Black",
    "Gloria Gaston",
    "Grace Shomsky",
    "Haegan Land",
    "Hoodie Strings",
    "Ike Schoenborn",
    "Isaac Kortz",
    "Isaac Skinner",
    "Jack Major",
    "Jacob Kwiatkowski",
    "Jana Stiffler",
    "Jasmine Zimmerman",
    "Jessalyn Rolf",
    "Joe Engle",
    "John DiPiazza",
    "John Lydel",
    "John Marchinda",
    "John Paul Sanders",
    "John Warner",
    "Jonathan Paredez",
    "Josh Ulman",
    "Josiah Miller",
    "Kaelan Miller",
    "Kate O'Donohue",
    "Levi Schoenborn",
    "Luke orPaul",
    "Maggie Prina",
    "Marnath Tuo",
    "Meghan VanDalen",
    "Molly Finkler",
    "Molly McCrory",
    "Morgan Duddles",
    "Natalie Fenske",
    "Natalie Sanders",
    "Nathan Ulman",
    "Noah Kwiatkowski",
    "Noah Lewandowsk",
    "Oliver Moore",
    "Owen Davies",
    "Polly Weis",
    "Sadie Hakes",
    "Selah Churchwell",
    "Silas Emery",
    "Sinead Noonan",
    "Stephanie DiPiazza",
    "Stratton Land",
    "Suzannah DiPiazza",
    "Thomas Prina",
    "Valley Duddles",
    "Wyatt Moore"
  ]}

*/

